# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json

updates:
    -   commit-message:
            prefix: chore(deps)
        directory: /
        package-ecosystem: github-actions
        schedule:
            interval: weekly

    -   commit-message:
            prefix: chore(deps)
        directory: /
        groups:
            tailwindcss:
                patterns:
                    - "@tailwindcss/*"
                    - tailwindcss
            typescript:
                patterns:
                    - "@types/*"
                    - typescript
        open-pull-requests-limit: 10
        package-ecosystem: npm
        schedule:
            interval: weekly

version: 2
